### ISSUE TITLE
Bug in learn_more pattern

### ISSUE THREAD

**Issue by stevemk14ebr** [learn-more/findpattern-bench#22]
The +3 increment on both findpattern implementations for learn_more can move beyond the string pattern null terminator. This can cause undesired memory faults or potentially extra loops. I've fixed it by calculating the pattern width dyanmically with added constraint that the ?? style must be used, and not a single ?

```
inline uint64_t findPattern(const uint64_t rangeStart, size_t len, const char* pattern)
{
	size_t l = strlen(pattern);

	// l = 2 * b + (b - 1) . 2 chars per byte + b - 1 spaces between
	size_t patSize = (l + 1) / 3;
	uint8_t* patt_base = (uint8_t*)_alloca(patSize + 1);
	uint8_t* msk_base = (uint8_t*)_alloca(patSize + 1);
	uint8_t* pat = patt_base;
	uint8_t* msk = msk_base;

	l = 0;
	while (patSize) {
		if (*(uint8_t*)pattern == (uint8_t)'\?') {
			*pat++ = 0;
			*msk++ = '?';
		} else {
			*pat++ = getByte(pattern);
			*msk++ = 'x';
		}
		pattern += 3;
		l++;
		patSize--;
	}

	if (l > len)
		return NULL;

	*msk = 0;
	pat = patt_base;
	msk = msk_base;
	for (size_t n = 0; n < (len - l); ++n)
	{
		if (isMatch((uint8_t*)(rangeStart + n), patt_base, msk_base)) {
			return rangeStart + n;
		}
	}
	return NULL;
}
```

**Comment by learn-more** [comment]
This is only an issue when the ?? is specified at the end of the string.
And ending a string with a wildcard does not make sense, since the pattern can then simply be shortened.

**Comment by stevemk14ebr** [comment]
this is my final modified implementation: https://github.com/stevemk14ebr/PolyHook_2_0/blob/bb97d61aeb9409c9c2146ae10a3fd3590cde5fe7/sources/Misc.cpp#L3

**Comment by learn-more** [comment]
Thanks :)

I do have another implementation that _should_ work.
